export async function seed(knex) {
  await knex("exercises").del();
  await knex("exercises").insert([
    {
      id: 1,
      name: "Push-up",
      body_part: "Upper Body",
      workout_type: "Strength",
      video_url: "/videos/push-ups.mp4",
      sets: 3,
      reps: 15,
      duration: "00:02:00",
      calories_burned: 50,
    },
    {
      id: 2,
      name: "Burpee",
      body_part: "Full Body",
      workout_type: "HIIT",
      video_url: "/videos/burpees.mp4",
      sets: 3,
      reps: 10,
      duration: "00:01:30",
      calories_burned: 60,
    },
    {
      id: 3,
      name: "Squat",
      body_part: "Lower Body",
      workout_type: "Strength",
      video_url: "/videos/squats.mp4",
      sets: 3,
      reps: 12,
      duration: "00:02:30",
      calories_burned: 80,
    },
    {
      id: 4,
      name: "Lunges",
      body_part: "Lower Body",
      workout_type: "Strength",
      video_url: "/videos/lunges.mp4",
      sets: 3,
      reps: 10,
      duration: "00:02:00",
      calories_burned: 70,
    },
    {
      id: 5,
      name: "Plank",
      body_part: "Core",
      workout_type: "HIIT",
      video_url: "/videos/plank.mp4",
      sets: 1,
      reps: 1,
      duration: "00:01:00",
      calories_burned: 30,
    },
    {
      id: 6,
      name: "Mountain Climbers",
      body_part: "Full Body",
      workout_type: "HIIT",
      video_url: "/videos/mountain_climbers.mp4",
      sets: 3,
      reps: 15,
      duration: "00:01:30",
      calories_burned: 60,
    },
    {
      id: 7,
      name: "Bicep Curls",
      body_part: "Upper Body",
      workout_type: "Strength",
      video_url: "/videos/bicep_curls.mp4",
      sets: 3,
      reps: 12,
      duration: "00:01:30",
      calories_burned: 50,
    },
    {
      id: 8,
      name: "Tricep Dips",
      body_part: "Upper Body",
      workout_type: "Strength",
      video_url: "/videos/tricep_dips.mp4",
      sets: 3,
      reps: 12,
      duration: "00:02:00",
      calories_burned: 60,
    },
    {
      id: 9,
      name: "Jumping Jacks",
      body_part: "Full Body",
      workout_type: "HIIT",
      video_url: "/videos/jumping_jacks.mp4",
      sets: 3,
      reps: 20,
      duration: "00:01:00",
      calories_burned: 40,
    },
    {
      id: 10,
      name: "Crunches",
      body_part: "Core",
      workout_type: "Strength",
      video_url: "/videos/crunches.mp4",
      sets: 3,
      reps: 15,
      duration: "00:01:30",
      calories_burned: 50,
    },
    {
      id: 11,
      name: "Jump Rope",
      body_part: "Full Body",
      workout_type: "Fat Burning",
      video_url: "/videos/jump_rope.mp4",
      sets: 4,
      reps: 50,
      duration: "00:03:00",
      calories_burned: 100,
    },
    {
      id: 12,
      name: "High Knees",
      body_part: "Legs",
      workout_type: "Fat Burning",
      video_url: "/videos/high_knees.mp4",
      sets: 3,
      reps: 40,
      duration: "00:02:30",
      calories_burned: 80,
    },
    {
      id: 13,
      name: "Yoga Stretch",
      body_part: "Full Body",
      workout_type: "Low Impact",
      video_url: "/videos/yoga_stretch.mp4",
      sets: 2,
      reps: 1,
      duration: "00:05:00",
      calories_burned: 40,
    },
    {
      id: 14,
      name: "Walking",
      body_part: "Full Body",
      workout_type: "Low Impact",
      video_url: "/videos/walking.mp4",
      sets: 1,
      reps: 1,
      duration: "00:30:00",
      calories_burned: 120,
    },
    {
      id: 15,
      name: "Jump Squats",
      body_part: "Lower Body",
      workout_type: "Fat Burning",
      video_url: "/videos/jump_squats.mp4",
      sets: 3,
      reps: 15,
      duration: "00:02:00",
      calories_burned: 85,
    },
    {
      id: 16,
      name: "Skater Jumps",
      body_part: "Full Body",
      workout_type: "Fat Burning",
      video_url: "/videos/skater_jumps.mp4",
      sets: 3,
      reps: 20,
      duration: "00:02:30",
      calories_burned: 90,
    },
    {
      id: 17,
      name: "Side Leg Raises",
      body_part: "Legs",
      workout_type: "Low Impact",
      video_url: "/videos/side_leg_raises.mp4",
      sets: 3,
      reps: 12,
      duration: "00:02:00",
      calories_burned: 40,
    },
    {
      id: 18,
      name: "Arm Circles",
      body_part: "Upper Body",
      workout_type: "Low Impact",
      video_url: "/videos/arm_circles.mp4",
      sets: 3,
      reps: 20,
      duration: "00:01:30",
      calories_burned: 30,
    },
  ]);
}
